### ISSUE TITLE
Detect when copied and original variable is used

### ISSUE THREAD

**Issue by SuperSandro2000** [karamaru-alpha/copyloopvar#8]
I have the following code which I extracted from a test:

```golang
		for _, req := range testRequests {
			failingReq := req // <----- here
			failingReq.ExpectBody = test.ErrorCode(keppel.ErrTooManyRequests)
			failingReq.ExpectStatus = http.StatusTooManyRequests
			failingReq.Check(t, h)

			s.Clock.StepBy(time.Second)
			req.Check(t, h)
		}
```

req gets copied and modified and both are used. I think the linter should ignore this or at least add an option to ignore it.

**Comment by karamaru-alpha** [comment]
@SuperSandro2000 
I apologize for the delayed response.
This linter has `ignore-alias` option. Have you tried it?👀

cf. https://golangci-lint.run/usage/linters/#copyloopvar
```yaml
linters:
  disable-all: true
  enable:
    - copyloopvar

linters-settings:
  copyloopvar:
    ignore-alias: true

```
